insert into trgovine (ime_trgovine, lokacija) values ('spar','Corfe Alley');
insert into trgovine (ime_trgovine, lokacija) values ('spar','Highlands Cliff');
insert into trgovine (ime_trgovine, lokacija) values ('spar','Broad Heights');
insert into trgovine (ime_trgovine, lokacija) values ('spar','Gibson Loke');
insert into trgovine (ime_trgovine, lokacija) values ('spar','Ellicks Close');
insert into trgovine (ime_trgovine, lokacija) values ('mercator','Hornhatch');
insert into trgovine (ime_trgovine, lokacija) values ('mercator','Laburnum Lane');
insert into trgovine (ime_trgovine, lokacija) values ('mercator','Thorpe Leys');
insert into trgovine (ime_trgovine, lokacija) values ('mercator','Waterside Boulevard');
insert into trgovine (ime_trgovine, lokacija) values ('mercator','Millbrook Market');
insert into trgovine (ime_trgovine, lokacija) values ('tus',' Beeches Oak');
insert into trgovine (ime_trgovine, lokacija) values ('tus','Priory Crescent');
insert into trgovine (ime_trgovine, lokacija) values ('hofer','Cromer Point');
insert into trgovine (ime_trgovine, lokacija) values ('hofer','Dingle Close');
insert into trgovine (ime_trgovine, lokacija) values ('hofer','Rydal Square');
insert into trgovine (ime_trgovine, lokacija) values ('hofer','Beechcroft Wynd');
insert into trgovine (ime_trgovine, lokacija) values ('lidl','Mount Pleasant Woodlands');
insert into trgovine (ime_trgovine, lokacija) values ('lidl','Priors Bridge');
insert into trgovine (ime_trgovine, lokacija) values ('lidl','Bull Isaf');
insert into trgovine (ime_trgovine, lokacija) values ('lidl','Bernard Fairway');
